var Strings = 
{
    DateVersion: '17/09/2019',
    AppName: 'Price Buddy',
    Name: 'Nome',
    Lastname: 'Sobrenome',
    Email: 'Email',
    Password: 'Senha',
    PasswordConfirmation: 'Confirmação da Senha',
    CellPhone: 'Celular',
    DoRegister: 'Cadastrar',
    Search: 'Pesquisar',
    InformProduct: 'Informe o Produto',
    Signin: 'Entrar',
    Login: 'Login',
    Establishments: 'Estabelecimentos',
    Products: 'Produtos',
    Product: 'Produto',
    Information: 'Informações',
    Map: 'Mapa',
    About: 'Sobre',
    MyProfile: 'Meu Perfil',
    Logout: 'Logout',
    FailureAPI: 'Falha na Comunicação com a API.',
    Warning: 'Atenção',
    Failure: 'Falha',
    DefaultMessageCalledAPIUser: 'Não foi possível efetuar o cadastro, verifique sua conexão e tente novamente.',
    DefaultMessageCalledAPILogin: 'Não foi possível efetuar o login, verifique sua conexão e tente novamente.',
    DefaultMessageCalledAPIEstablishment: 'Não foi possível carregar os estabelecimentos, verifique sua conexão e tente novamente.',
    DefaultMessageCalledAPIProduct: 'Não foi possível carregar os produtos, verifique sua conexão e tente novamente.',
    MessageFailureRegisterUser: 'Email já cadastrado, verifique seus dados e tente novamente.',
    Success: 'Sucesso',
    MessageSuccessRegisterUser: 'Usuário adicionado com sucesso.',
    Register: 'Cadastro',
    EnterName: 'Informe o Nome.',
    EnterProduct: 'Informe o Produto.',
    EnterLastname: 'Informe o Sobrenome.',
    InvalidEmail: 'Email inválido.',
    EnterEmail: 'Informe o Email.',
    EnterPassword: 'Informe a Senha.',
    EnterPasswordConfirmation: 'Informe a Confirmação da Senha.',
    PasswordsNotMatch: 'Senhas não Conferem.',
    PasswordLeastSixChars: 'Senha deve ter no mínimo 6 caracteres.',
    EnterCellPhoneNumber: 'Informe o Número de Celular.',
    EnterCellPhoneNumberCorrectly: 'Digite corretamente o Número de Celular.',
    EstablishmentNotFound: 'Não foi encontrado nenhum Estabelecimento',
    SearchProduct: 'Informe o nome ou código de barras para consultar um produto',
    ProductInformationFalied: 'Não foi possível carregar as informações do Produto',
    EstablishmentNoProducts: 'Não foi encontrado nenhum Produto',
    Price: 'Preço',
    Weight: 'Peso',
    Description: 'Descrição',
    Establishment: 'Estabelecimento',
    Distance: 'Distância',
    Address: 'Endereço',
    Phone: 'Telefone',
    City: 'Cidade',
    ProductNotFound: 'Não foi encontrado nenhum produto, verifique o valor digitado e tente novamente.',
}

export default Strings
